---
functional:
  - Успешная авторизация пользователя
  - Успешное создание новой игры
  - Успешное подключение второго игрока
  - Успешное ведение игры двумя игроками в режиме онлайн
  - Корректное функционирование кнопки для проверки решения игрока
  - Корректное функционирование личного кабинета
  - Корректное функционирование чата
  - Корректное функционирование поиска и фильтров
  - Корректное функционирование кнопки возврата на главную страницу
  - Возможность выбора русского и английского языка в задании
  - Возможность выбора языка программирования
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Пользовательский интерфейс должен быть в умеренной цветовой гамме
